mvn clean install
mvn clean install -f ezyfox-versions
mvn clean install -f ezyfox-util
mvn clean install -f ezyfox-tools
mvn clean install -f ezyfox-io
mvn clean install -f ezyfox-concurrent
mvn clean install -f ezyfox-security
mvn clean install -f ezyfox-common
mvn clean install -f ezyfox-codec
mvn clean install -f ezyfox-binding
mvn clean install -f ezyfox-bean
mvn clean install -f ezyfox-json
mvn clean install -f ezyfox-mapping
mvn clean install -f ezyfox-jackson
mvn clean install -f ezyfox-msgpack
mvn clean install -f ezyfox-binding-codec
mvn clean install -f ezyfox-identifier
mvn clean install -f ezyfox-message
mvn clean install -f ezyfox-data
mvn clean install -f ezyfox-database
mvn clean install -f ezyfox-monitor