<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tvd12</groupId>
        <artifactId>ezyfox-versions</artifactId>
        <version>1.3.1</version>
    </parent>
    <artifactId>ezyfox-mapping</artifactId>
    <name>ezyfox-mapping</name>
    <description>
        Annotation-driven object mapping utilities for converting between data formats in EzyFox.
    </description>
    <url>https://youngmonkeys.org/projects/ezyfox-library</url>

    <licenses>
        <license>
            <name>Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git@github.com:youngmonkeys/ezyfox.git</connection>
        <developerConnection>scm:git:git@github.com:youngmonkeys/ezyfox.git</developerConnection>
        <url>https://github.com/youngmonkeys/ezyfox</url>
    </scm>

    <developers>
        <developer>
            <name>Ta Van Dung</name>
            <email>ta.van.dung@youngmonkeys.org</email>
            <organization>Young Monkeys</organization>
            <organizationUrl>https://youngmonkeys.org/</organizationUrl>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>com.tvd12</groupId>
            <artifactId>ezyfox-json</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>${jaxb.version}</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>${jaxb.runtime.version}</version>
        </dependency>
    </dependencies>

</project>
